version: "3"

vars:
  COMPOSE_FILE: ./docker/docker-compose.dev-aio.yml

tasks:
  all:start:
    desc: Start backend, frontend, and docs services in dev AIO stack (detached)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d headendarr frontend docs

  all:stop:
    desc: Stop backend, frontend, and docs services in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop headendarr frontend docs

  backend:start:
    desc: Start backend (tic) service in dev AIO stack (detached)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d headendarr

  backend:stop:
    desc: Stop backend (tic) service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop headendarr

  backend:logs:
    desc: Tail backend (tic) service logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} headendarr

  backend:build:
    desc: Build backend (tic) service image
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} build headendarr

  backend:migrate:rollback-last:
    desc: Roll back the most recent Alembic migration using a one-off backend (tic) container
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm -e SKIP_MIGRATIONS=true -e ROLLBACK_LAST_MIGRATION=true headendarr

  backend:migrate:current:
    desc: Print the current Alembic migration revision using a one-off backend (tic) container
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm -e SKIP_MIGRATIONS=true -e PRINT_CURRENT_MIGRATION=true headendarr

  frontend:start:
    desc: Start frontend dev server service in dev AIO stack (detached)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d frontend

  frontend:stop:
    desc: Stop frontend dev server service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop frontend

  frontend:logs:
    desc: Tail frontend dev server logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} frontend

  frontend:clean:
    desc: Clear Quasar CLI caches for frontend
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm frontend bash -lc "npx quasar clean"

  frontend:build:
    desc: Build frontend (Quasar SPA) for backend serving
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm frontend bash -lc "npx quasar build"

  docs:start:
    desc: Start docs dev server service in dev AIO stack (detached)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d docs

  docs:stop:
    desc: Stop docs dev server service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop docs
      - docker compose -f {{.COMPOSE_FILE}} stop docs-static

  docs:logs:
    desc: Tail docs dev server logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} docs

  docs:build:
    desc: Build static documentation pages
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm docs bash -lc "npm run build"

  docs:static:start:
    desc: Start docs static server service in dev AIO stack (detached)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d docs-static

  docs:static:stop:
    desc: Stop docs static server service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop docs-static

  docs:static:logs:
    desc: Tail docs static server logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} docs-static

  set-version:
    desc: Set the version in frontend/package.json
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "Error: No version provided. Usage: task set-version -- 1.0.1"
          exit 1
        fi
        cd frontend && npm version "{{.CLI_ARGS}}" --no-git-tag-version
        echo "Version updated to {{.CLI_ARGS}} in frontend/package.json and package-lock.json"
