version: "3"

vars:
  COMPOSE_FILE: ./docker/docker-compose.dev-aio.yml

tasks:
  init:
    desc: Initialize local cache directories
    cmds:
      - mkdir -p temp/cache/.npm temp/cache/.npm-global temp/cache/venv-backend

  all:start:
    desc: Start backend, frontend, and docs services in dev AIO stack (detached)
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d headendarr frontend docs

  all:stop:
    desc: Stop backend, frontend, and docs services in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop headendarr frontend docs

  backend:start:
    desc: Start backend (tic) service in dev AIO stack (detached)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d headendarr

  backend:stop:
    desc: Stop backend (tic) service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop headendarr

  backend:logs:
    desc: Tail backend (tic) service logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} headendarr

  backend:build:
    desc: Build backend (tic) service image
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} build headendarr

  backend:upgrade:
    desc: Upgrade backend Python dependencies using pip-compile and pip-audit
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm --entrypoint="" --user 1000:1000 -v ./temp/cache/venv-backend:/var/venv-temp headendarr bash -c "[ -f /var/venv-temp/bin/activate ] || (python3 -m venv --without-pip /var/venv-temp && . /var/venv-temp/bin/activate && curl -sS https://bootstrap.pypa.io/get-pip.py | python3) && . /var/venv-temp/bin/activate && pip install --upgrade pip pip-tools pip-audit && pip-compile ./requirements.in --upgrade && pip install -r ./requirements.txt -r ./requirements-dev.txt && pip-audit"

  backend:migrate:rollback-last:
    desc: Roll back the most recent Alembic migration using a one-off backend (tic) container
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm -e SKIP_MIGRATIONS=true -e ROLLBACK_LAST_MIGRATION=true headendarr

  backend:migrate:current:
    desc: Print the current Alembic migration revision using a one-off backend (tic) container
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm -e SKIP_MIGRATIONS=true -e PRINT_CURRENT_MIGRATION=true headendarr

  frontend:start:
    desc: Start frontend dev server service in dev AIO stack (detached)
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d frontend

  frontend:stop:
    desc: Stop frontend dev server service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop frontend

  frontend:logs:
    desc: Tail frontend dev server logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} frontend

  frontend:clean:
    desc: Clear Quasar CLI caches for frontend
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm frontend bash -lc "npx quasar clean"

  frontend:build:
    desc: Build frontend (Quasar SPA) for backend serving
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm frontend bash -lc "npx quasar build"

  frontend:upgrade:
    desc: Upgrade Quasar and npm dependencies
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm frontend bash -c "npm audit || true"
      - docker compose -f {{.COMPOSE_FILE}} run --rm frontend bash -c "npm install -g @quasar/cli && /home/node/.npm-global/bin/quasar upgrade -i && npm update && npm audit fix"

  docs:start:
    desc: Start docs dev server service in dev AIO stack (detached)
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d docs

  docs:stop:
    desc: Stop docs dev server service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop docs
      - docker compose -f {{.COMPOSE_FILE}} stop docs-static

  docs:logs:
    desc: Tail docs dev server logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} docs

  docs:build:
    desc: Build static documentation pages
    deps: [init]
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} run --rm docs bash -lc "npm run build"

  docs:static:start:
    desc: Start docs static server service in dev AIO stack (detached)
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} up -d docs-static

  docs:static:stop:
    desc: Stop docs static server service in dev AIO stack
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} stop docs-static

  docs:static:logs:
    desc: Tail docs static server logs
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} logs {{.CLI_ARGS}} docs-static

  bump-version:
    desc: Bump frontend version (default patch, or pass major/minor/patch)
    cmds:
      - |
        bump_type="{{.CLI_ARGS}}"
        if [ -z "$bump_type" ]; then
          bump_type="patch"
        fi
        case "$bump_type" in
          patch|minor|major) ;;
          *)
            echo "Error: Invalid bump type '$bump_type'. Use: patch, minor, or major."
            echo "Usage: task bump-version [-- patch|minor|major]"
            exit 1
            ;;
        esac

        npm --prefix frontend version "$bump_type" --no-git-tag-version
        new_version=$(node -p "require('./frontend/package.json').version")
        git add frontend/package.json frontend/package-lock.json
        echo "Version bumped with '$bump_type' in frontend/package.json and package-lock.json"
        echo "Staged: frontend/package.json frontend/package-lock.json"
        echo "Next run:"
        echo "> git commit -m 'Bump version $new_version'"
